### ISSUE TITLE
Make vote text more accessible

### ISSUE THREAD

**Issue by luisivan** [aragon/AGPs#39]
Instead of the usual *"Should AGP-X be approved?"*, maybe we could add a short title before that question, like *"Aragon Black: Should AGP-X be approved?"* or *"Separation of State and Church: ..."*

**Comment by john-light** [comment]
@luisivan  great suggestion, thank you. For AGP-1 the question was:

> Should the Aragon project adopt AGP-1 as the Aragon Governance Proposal process?

I consider it an oversight that the proposals in ANV-01 were not expressed in a similar way to reference the full title of the proposal, rather than a conscious decision. We can certainly make it a convention to list the full AGP name and number, such as:

> Do you approve AGP-9: The Separation of Church, State, and Network? [link]

**Comment by luisivan** [comment]
That is perfect
