### ISSUE TITLE
Association: Prioritise Delegate Voting

### ISSUE THREAD

**Issue by pythonpete32** [aragon/AGPs#62]
# AGP-X:  TO PRIORITISE DELEGATE VOTING

Version: 0.01
## Description
Delegate voting as a primitive has clear benefits,  potentially compounded with staking, bonding curves, futarchy, as well as the others, being developed.

Furthermore, it increases the influence of community members aligned with the Aragon vision and manifesto but have little plutocratic Power.

## Motivation
voter turnout at the first round of voting was extremely low, while the turnout has increased in the most recent round of voting 4.8% is still incredibly low leaves us open to attack.

then there is the uncomfortable truth that one whale did control the outcome of several proposals. if the turnout remains roughly the same next time around, A few $100k's can buy a controversial AGP. Personally, I was for #41 but if it got flipped last minute by a whale, that would have been a PR disaster.

One of the biggest factors behind this simply that voting sucks, It costs money and its bandwidth intensive. Furthermore, it doesn't scale well (in attention terms). Of course, waiting 30min for the app to load isn't exactly great UX, however, these are technical issues which I'm confident will be resolved.

I'm super excited about the Level K Futarchy app, governing the AGP process with futarchy 😍🤓🚀🦅. But there are questions of liquidity that I'm not sure have been solved. Personally, I'd prefer the AGP process to run this way but I'm not sure how long it would take to do it safely? In the meantime, we need to explore other options. We should not have all our eggs in one basket (pun intended!)

**Comment by julianbrooks** [comment]
I would support our Coop DAO getting behind this proposal, with a couple of caveats:
1) some research is needed to be sure of current thinking and any approaches to implementing DV in the wider Aragon Network (make sure we're not treading on toes:)
2) I'd tone down some of the language above :D (e.g. I think some approaches to engaging with delay times for 'app-loading' have already been made).

3) 'how and who and with what' would you propose to implement DV with?

It' s good though, defo +1

**Comment by pythonpete32** [comment]
@julianbrooks 



> some research is needed to be sure of current thinking and any approaches to implementing DV in the wider Aragon Network (make sure we're not treading on toes:)


AFAIK @facuspagnuolo is working on it for Aragon One and it is on the roadmap for this year. However, release features get pushed back. The point of this proposal is we would want the association to priorities this R&D. Either get facu working on it full time, maybe with someone else or even in collaboration with another flock team



> I'd tone down some of the languages above



For me, this is a very serious issue, its not comfortable but it is a fact. One whale did decide the outcome of several AGPs. 
Yes, there has been talking of commit/review and delay times but these are not even proposals yet and they don't change the fundamental problem of voter turnout and buying AGPs.
IMO commit/reveal is worse. It's 2 transactions, more complicated and therefore more friction. At the same time, it wont stop someone buying up ANT to push through their proposal



> 'how and who and with what' would you propose to implement DV with?



This proposal is simply to prioritise research. This would be a benefit across the whole ecosystem, but specifically for the AGP process. Personally, I'd prefer Futarchy for governance over the AGP process, but that isn't a guarantee and we need other alternatives. 
I know @lkngtn is a fan of quadratic voting generaly that's also another option but id like to see DV prioritised

**Comment by pythonpete32** [comment]
Also, see the coop potentially playing a big role here. As the coop matures leaders from the community would likely accumulate delegations

**Comment by julianbrooks** [comment]
Hard to argue with any of the above @pythonpete32  - and great to gain a sense of your drive and passion for this - props. Important when constructing the proposal to cover many bases. I do think in a purposeful Plutocracy some of what;s happening is unavoidable. I think too that for many holders, ANT is a speculative commodity (& has provided funding for wonderful things:) - ally that to complexities of getting the token out of storage and perhaps we shouldn't be surprised at the current predicament but yes, absolutely, anything we can do to alleviate this situation should be explored (my 2sats anyhow:)

**Comment by burrrata** [comment]
@pythonpete32 I think it would be great to make DV more of a research/engineering priority. I'm not an expert on the AGP process, but from the perspective of a reader it would help me if the Description section more clearly defined exactly what the goal was. Also, it would be helpful if there was a call to action within the proposal listing concrete steps that could be take to move towards that goal. These steps don't have to be as detailed as a Nest Grant, but outlining a few general steps could go a long way to help make this a reality. Or at least it would go a long way towards helping me see how we could make this a reality and what the actual ask is.

**Comment by pythonpete32** [comment]
Thanks for the feedback @julianbrooks and @burrrata ill update the proposal with that feedback in mind 

> I do think in a purposeful Plutocracy some of
> what's happening is unavoidable.

Totally, not against plutocracy perse, token weighted voting is a plutocratic system. It's just that it needs to be tempered to align the interests of all stakeholders. But that isn't even the issue here, the issue is preventing an attack vector that dosn't seem so theoretical anymore 

[This thread](https://github.com/aragon/governance/issues/1) from the appreciated governance repo covers some if these topics. The adversary, in question was an exchange (voting power with nothing at stake) however this applies to a much wider class of actors given how low quorum is as well as the fact that in our current system, you can sell your stake before you use your voting power

**Comment by lkngtn** [comment]
Strongly support prioritizing delegate voting but wanted to add a few thoughts. 

- A decisive swing voter isn't necessarily a problem. I wouldn't consider the whale swinging votes by actively participating in the process an attack. I think it makes sense to frame this around the potential benefits of delegation for users rather than framing it as a solution to mitigate decisive voters. 
- as mentioned in the thread delegate voting is already on Aragon One's roadmap and actively being worked on. Depending on how this is implemented it could be an upgrade to the existing voting app, a new alternative voting app, or done through proxy contracts such that the delegation could occur even with the current voting app without any upgrades. 

 While I don't really see the harm in an AGP like this, I wonder if there are not better ways for users to help participate and signal priorities in a more continuous fashion, particularly for items which are already on the roadmap.

**Comment by pythonpete32** [comment]
Thanks for comments @lkington

> I wouldn't consider the whale swinging votes by actively participating in the process an attack.


Your right, a decisive swing vote is not necessarily an attack. Nor am I against whales participating, they have more at stake and rightly have a larger influence.

However, the point being made is valid. Right now it is possible to open an AGP requesting funding for another project, buy a large amount of ANT, sell that ANT immediately after the snapshot of accounts is made, and flip the result last minute, even if it is against the interest of real Aragon stakeholders. This I would consider an attack and a real possibility. 

> I wonder if there are not better ways for users to help participate and signal priorities in a more continuous fashion, particularly for items which are already on the roadmap.

Not sure what you mean by continuous but there are many things on the road map, A1s priorities for each item may not necessarily be that of the users. I think it's a perfectly legitimate use of the AGP process

> I think it makes sense to frame this around the potential benefits of delegation for users rather than framing it as a solution to mitigate decisive votes.


You are right, framing DV as a solution is not correct and was not my intention. in actuality, DV is not a direct solution at all. What it does is reduce friction in participation and thus make this kind of attack more expensive. 


I want to see DV prioritised, I am extremely uncomfortable with the fragility of the system. I would be surprised if I was alone in this perception.  This should probably be a separate AGP all together

**Comment by lkngtn** [comment]
> However, the point being made is valid. Right now it is possible to open an AGP requesting funding for another project, buy a large amount of ANT, sell that ANT immediately after the snapshot of accounts is made, and flip the result last minute, even if it is against the interest of real Aragon stakeholders. This I would consider an attack and a real possibility. 

I agree it's a valid concern, and a good reason to prioritize Delegative Voting. Just wan't to avoid the message that a whale (or perhaps even influential delegate) having a decisive vote is necessarily a bad thing. 

The root of the issue (imo) is that our ability to protect the interests of minority/passive participants in the process is heavily reliant on the discretion/judgement of the association. This may not be the best solution long term, and efforts to solve this issue in a better and more decentralized way are being prioritized (specifically the court), but in the meantime the association review step of the AGP process is intended to provide some level of safety and I think does a reasonable job of protecting the process against malicious attacks like the one you have described. 

> Not sure what you mean by continuous but there are many things on the road map, A1s priorities for each item may not necessarily be that of the users. I think it's a perfectly legitimate use of the AGP process 

I'm not saying it is not a legitimate use of the AGP process (tbh it might not be because the association track is for association policy and the association doesn't have an R&D budget to prioritize (perhaps you could count nest)... but that wasn't the point I was trying to make). I was just trying to point out that it may not be the most efficient/effective way to communicate to a flock team that you think something that is on their roadmap should be more of a priority than it currently is. 

It doesn't require an AGP for the Aragon One team to adjust their priorities, and I haven't seen anything to indicate that they are not willing to accept feedback on releases. In fact there have been multiple posts on the forum discussing scope and planning for releases (https://forum.aragon.org/t/aragon-one-product-scope-for-0-8/741, https://forum.aragon.org/t/aragon-one-product-scope-for-0-7-x/739). The AGP process is on a quarterly cadence, it seems like something like this is important discussion to have, and it would be a shame if people in the community feel they can **only** engage with flock teams by way of AGPs. 

> I want to see DV prioritised, and I am extremely uncomfortable with the fragility of the system. I would be surprised if I was alone in this perception. This should probably be a separate AGP all together

I agree and I don't think you are alone, it seems the result of the last ANV definitely highlighted some issues that we need to work to address! 

However if the intention isn't to change association policy but simply provide a way for ANT holders to signal the importance of delegative voting, perhaps the proclamation track would be more appropriate? And in the mean time perhaps creating a forum thread to discuss the importance of DV and suggest that Aragon One provide a progress update on development,  or the push wider community make it a higher priority.

**Comment by burrrata** [comment]
> I wonder if there are not better ways for users to help participate and signal priorities in a more continuous fashion, particularly for items which are already on the roadmap.

https://github.com/aragon/AGPs/issues/51
https://forum.aragon.org/t/meta-separation-of-signalling-and-voting-51/871

**Comment by pythonpete32** [comment]
Just wan't to avoid the message that a whale (or perhaps even influential delegate) having a decisive vote is necessarily a bad thing.


Sure, there isn't anything necessarily wrong with a whale swinging a vote. But do I think there is a qualitative difference with a delegate swinging a vote, firstly they represent many stakeholders and secondly there is a bit more transparency.

Let me make myself clear. What happened with the votes were not an attack at all. The problem was a matter of optics. What happened highlighted that an attack was possible and profitable

[the association] I think does a reasonable job of protecting the process against malicious attacks like the one you have described.


I think so too. And I have full trust in them because I know a lot of them, however, most don't. They shouldn't have to.

it seems like something like this is an important discussion to have, and it would be a shame if people in the community feel they can only engage with flock teams by way of AGPs.


Your right, I chose to use the AGP process because it is the most visible way of signalling to flock teams and the community. Sure there is the forum, probably should have started there.

At the moment, does a legitimate process for signalling exist that is as widely publicized and participated in as ANV? If not, then maybe it makes sense to create a "Meta Track" proposal to create a "Signalling Track" in the ANV process. pythonpete32 I'd be happy to draft something like that with you if you think it would be valuable?


Definitely, ill catch up with you later and we can start mapping it out

**Comment by john-light** [comment]
@pythonpete32 Delegated voting is currently still on the Aragon One roadmap (as seen in the Aragon Network tab [here](https://aragon.org/project/roadmap/)). You may also be interested in jumping into [this discussion](https://forum.aragon.org/t/voting-v1-single-delegation/440) in the forum.

**Comment by pythonpete32** [comment]
Considering the contracts are already finished and only front end needs building, as well as not having a good track for this proposal i am closing this issue for now. After speaking with various members within flock teams, i am confident DV will be coming to Aragon shortly anyway
